public enum Types {
    TSHIRT, TANK_TOP, LONG_SLEEVE_SHIRT, SHORT_SLEEVE_SHIRT,
    BLOUSE, HOODIE, JACKET, SWEATSHIRT, SWEATER, COAT,
    PANTS, JEANS, SHORTS, SKIRT, SNEAKERS, DRESS_SHOES, BOOTS,
    HEELS, SLIPPERS, SANDALS, HATS, SUNGLASSES, BELTS, GLOVES, SCARVES,
    DRESS, COVERALLS, OVERALLS, JUMPSUIT, UNDERWEAR, SOCKS, BRA, OTHER
}
